%YAML:1.0

# Camera Parameters. Adjust them!

Camera.rows: 480
Camera.cols: 640

# Camera calibration parameters (OpenCV) 
Camera.fx: 508.353158
Camera.fy: 510.167196
Camera.cx: 311.288297
Camera.cy: 235.728826

# Camera distortion paremeters (OpenCV) --
Camera.k1: 0.043922
Camera.k2: -0.016877
Camera.p1: 0.002922
Camera.p2: -0.005741

# Camera frames per second 
Camera.fps: 24.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
### Changing the parameters below could seriously degradate the performance of the system

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold (lower less restrictive)			
ORBextractor.fastTh: 20

# ORB Extractor: Score to sort features. 0 -> Harris Score, 1 -> FAST Score			
ORBextractor.nScoreType: 1

# Constant Velocity Motion Model (0 - disabled, 1 - enabled [recommended])
UseMotionModel: 1
